In [38]:
import pandas as pd
import numpy as np

In [11]:
X = pd.read_csv("../data/processed/X_docetaxel.csv")
y = pd.read_csv("../data/processed/y_docetaxel.csv")

In [12]:
X = X.set_index('SANGER_MODEL_ID')
X.head()

,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2ML1-AS1,A2ML1-AS2,A2MP1,A3GALT2,...,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11AP1,ZYG11B,ZYX,ZZEF1,ZZZ3
SANGER_MODEL_ID,,,,,,,,,,,,,,,,,,,,,
SIDM01132,5.1375,3.3840,0.0000,0.6135,0.0000,0.0426,0.0000,0.0,0.0000,0.0841,...,6.1305,0.4751,1.8992,3.7623,0.9928,0.0,2.8258,6.4130,4.1554,4.0575
SIDM00848,4.8689,3.4476,0.0000,1.9964,0.1243,3.1890,0.0000,0.0,0.0000,0.0841,...,7.0915,1.6826,2.3306,5.1863,0.0841,0.0,3.0993,5.5242,3.6064,4.5211
SIDM00263,5.0365,3.5558,0.0144,3.9855,0.2987,5.7968,0.0566,0.0,0.1375,0.1110,...,5.6966,2.9486,3.3923,6.5963,4.1787,0.0,4.6809,6.3778,4.5759,5.6946
SIDM00269,4.5497,3.8001,0.0841,3.2157,0.0566,0.5753,0.0000,0.0,0.0841,0.1506,...,4.5392,2.8298,3.4128,6.7827,2.3190,0.0,4.2141,9.0105,4.9340,5.4561
SIDM00203,4.2250,3.2095,0.0144,0.5059,0.0976,2.8156,0.0000,0.0,0.0704,0.2141,...,6.4510,2.4957,3.4764,5.3071,3.0321,0.0,4.4731,6.9529,4.3590,5.3366

In [13]:
y = y.set_index('SANGER_MODEL_ID')
y.head()

                      AUC
SANGER_MODEL_ID
SIDM01132        0.267990
SIDM00848        0.105028
SIDM00263        0.195845
SIDM00269        0.082177
SIDM00203        0.302620

In [14]:
print(X.shape)
print(y.shape)

print("Missing values in X:", X.isna().sum().sum())
print("Missing values in y:", y.isna().sum().sum())

(651, 36417)
(651, 1)
Missing values in X: 0
Missing values in y: 0

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split (
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [16]:
print("Training samples:", X_train.shape[0])
print("Test samples:", X_test.shape[0])

Training samples: 520
Test samples: 131

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [44]:
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()

linear_model.fit(X_train_scaled, y_train)

LinearRegression()

In [45]:
y_pred_linear = linear_model.predict(X_test_scaled)

In [52]:
from sklearn.metrics import root_mean_squared_error, mean_absolute_error, r2_score

rmse_linear = root_mean_squared_error(
    y_test,
    y_pred_linear,
)

mae_linear = mean_absolute_error(
    y_test, 
    y_pred_linear
)

r2_linear = r2_score(
    y_test, 
    y_pred_linear
)

print("Linear Regression")
print("RMSE: ", rmse_linear)
print("MAE:", mae_linear)
print("R²:", r2_linear)

Linear Regression
RMSE:  0.27365430143375075
MAE: 0.2198595584503373
R²: 0.1721344702463099

In [66]:
# Linear Regression training predictions
y_train_pred_linear = linear_model.predict(X_train_scaled)

train_r2_linear = r2_score(
    y_train,
    y_train_pred_linear
)

print("Linear Regression Train R²:", train_r2_linear)
print("Linear Regression Test R²:", r2_linear)

Linear Regression Train R²: 1.0
Linear Regression Test R²: 0.1721344702463099

In [21]:
y_train_1d = y_train.values.ravel()
y_test_1d = y_test.values.ravel()

y_train_1d.shape
y_test_1d.shape

(131,)

In [57]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train_1d)

RandomForestRegressor(n_estimators=300, n_jobs=-1, random_state=42)

In [58]:
y_pred_rf = rf_model.predict(X_test)

In [67]:
rmse_rf = root_mean_squared_error (
    y_test,
    y_pred_rf
)

mae_rf = mean_absolute_error (
    y_test,
    y_pred_rf
)

r2_rf = r2_score (
    y_test,
    y_pred_rf
)

print("Random Forest")
print("RMSE: ", rmse_rf)
print("MAE: ", mae_rf)
print("R2: ", r2_rf)

Random Forest
RMSE:  0.27764103428235126
MAE:  0.2399737479389313
R2:  0.14783724416792132

In [71]:
y_train_pred_rf = rf_model.predict(X_train)

train_r2_rf = r2_score (
    y_train,
    y_train_pred_rf
)

print("Random Forest Train R²:", train_r2_rf)
print("Random Forest Test R²:", r2_rf)

Random Forest Train R²: 0.897191065577738
Random Forest Test R²: 0.14783724416792132

In [19]:
import torch

print(torch.__version__)

2.2.2

In [22]:
print("X_train:", X_train_scaled.shape)
print("X_test:", X_test_scaled.shape)
print("y_train:", y_train_1d.shape)
print("y_test:", y_test_1d.shape)

X_train: (520, 36417)
X_test: (131, 36417)
y_train: (520,)
y_test: (131,)

In [23]:
X_train_tensor = torch.tensor(
    X_train_scaled,
    dtype=torch.float32
)

X_test_tensor = torch.tensor(
    X_test_scaled,
    dtype=torch.float32
)

In [24]:
y_train_tensor = torch.tensor(
    y_train_1d,
    dtype=torch.float32
).reshape(-1, 1)

y_test_tensor = torch.tensor(
    y_test_1d,
    dtype=torch.float32
).reshape(-1, 1)

In [25]:
print(X_train_tensor.shape)
print(y_train_tensor.shape)

torch.Size([520, 36417])
torch.Size([520, 1])

In [26]:
import torch.nn as nn

In [30]:
class MLP(nn.Module):

    def __init__(self, input_size):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(input_size, 128),
            nn.ReLU(),

            nn.Linear(128, 64),
            nn.ReLU(),

            nn.Linear(64, 1)
        )

    def forward(self, x):
        return self.network(x)

In [31]:
input_size = X_train_tensor.shape[1]

model = MLP(input_size)

print(model)

MLP(
  (network): Sequential(
    (0): Linear(in_features=36417, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=1, bias=True)
  )
)

In [33]:
loss_function = nn.MSELoss()

MSELoss()

In [34]:
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)

In [35]:
num_epochs = 100

for epoch in range(num_epochs):

    # Forward pass
    predictions = model(X_train_tensor)

    # Calculate loss
    loss = loss_function(
        predictions,
        y_train_tensor
    )

    # Clear previous gradients
    optimizer.zero_grad()

    # Backpropagation
    loss.backward()

    # Update weights
    optimizer.step()

    if (epoch + 1) % 10 == 0:
        print(
            f"Epoch {epoch + 1}/{num_epochs}, "
            f"Loss: {loss.item():.4f}"
        )

Epoch 10/100, Loss: 0.2792
Epoch 20/100, Loss: 0.0453
Epoch 30/100, Loss: 0.0487
Epoch 40/100, Loss: 0.0116
Epoch 50/100, Loss: 0.0115
Epoch 60/100, Loss: 0.0022
Epoch 70/100, Loss: 0.0881
Epoch 80/100, Loss: 0.0027
Epoch 90/100, Loss: 0.0082
Epoch 100/100, Loss: 0.0004

In [48]:
model.eval()

with torch.no_grad():
    y_pred_mlp = model(X_test_tensor)

y_pred_mlp = y_pred_mlp.detach().cpu().tolist()

In [50]:
from sklearn.metrics import (
    root_mean_squared_error,
    mean_absolute_error,
    r2_score
)

rmse_mlp = root_mean_squared_error(
    y_test,
    y_pred_mlp
)

mae_mlp = mean_absolute_error(
    y_test,
    y_pred_mlp
)

r2_mlp = r2_score(
    y_test,
    y_pred_mlp
)

print("PyTorch MLP")
print("RMSE:", rmse_mlp)
print("MAE:", mae_mlp)
print("R²:", r2_mlp)

PyTorch MLP
RMSE: 0.7909909299443691
MAE: 0.5565811887128737
R²: -5.916689010141342

In [51]:
# find train and test R^2