In [66]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

In [67]:
X = pd.read_csv("../data/processed/X_docetaxel.csv")
y = pd.read_csv("../data/processed/y_docetaxel.csv")

In [68]:
X = X.set_index('SANGER_MODEL_ID')
y = y.set_index('SANGER_MODEL_ID')

In [69]:
X.head()

,A1BG,A1BG-AS1,A1CF,A2M,A2M-AS1,A2ML1,A2ML1-AS1,A2ML1-AS2,A2MP1,A3GALT2,...,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11AP1,ZYG11B,ZYX,ZZEF1,ZZZ3
SANGER_MODEL_ID,,,,,,,,,,,,,,,,,,,,,
SIDM01132,5.1375,3.3840,0.0000,0.6135,0.0000,0.0426,0.0000,0.0,0.0000,0.0841,...,6.1305,0.4751,1.8992,3.7623,0.9928,0.0,2.8258,6.4130,4.1554,4.0575
SIDM00848,4.8689,3.4476,0.0000,1.9964,0.1243,3.1890,0.0000,0.0,0.0000,0.0841,...,7.0915,1.6826,2.3306,5.1863,0.0841,0.0,3.0993,5.5242,3.6064,4.5211
SIDM00263,5.0365,3.5558,0.0144,3.9855,0.2987,5.7968,0.0566,0.0,0.1375,0.1110,...,5.6966,2.9486,3.3923,6.5963,4.1787,0.0,4.6809,6.3778,4.5759,5.6946
SIDM00269,4.5497,3.8001,0.0841,3.2157,0.0566,0.5753,0.0000,0.0,0.0841,0.1506,...,4.5392,2.8298,3.4128,6.7827,2.3190,0.0,4.2141,9.0105,4.9340,5.4561
SIDM00203,4.2250,3.2095,0.0144,0.5059,0.0976,2.8156,0.0000,0.0,0.0704,0.2141,...,6.4510,2.4957,3.4764,5.3071,3.0321,0.0,4.4731,6.9529,4.3590,5.3366

In [70]:
y.head()

                      AUC
SANGER_MODEL_ID
SIDM01132        0.267990
SIDM00848        0.105028
SIDM00263        0.195845
SIDM00269        0.082177
SIDM00203        0.302620

In [71]:
print("X Shape:", X.shape)
print("y shape:", y.shape)

X Shape: (651, 36417)
y shape: (651, 1)

In [72]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [73]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [74]:
print("Ridge Regression:")
print()

alphas = [0.01, 0.1, 1, 10, 100]
results = []

for alpha in alphas:

    ridge_model = Ridge(alpha)

    ridge_model.fit(X_train_scaled, y_train.values.ravel())

    y_test_ridge = ridge_model.predict(X_test_scaled)
    y_train_ridge = ridge_model.predict(X_train_scaled)

    rmse_ridge = root_mean_squared_error(y_test, y_test_ridge)
    mae_ridge = mean_absolute_error(y_test, y_test_ridge)
    test_r2_ridge = r2_score(y_test, y_test_ridge)
    train_r2_ridge = r2_score(y_train, y_train_ridge)


    results.append({
        "Alpha": alpha,
        "Train R²": train_r2_ridge,
        "Test R²": test_r2_ridge,
        "RMSE": rmse_ridge,
        "MAE": mae_ridge
        
    })

ridge_results = pd.DataFrame(results)

ridge_results

Ridge Regression:

    Alpha  Train R²   Test R²      RMSE       MAE
0    0.01  1.000000  0.172134  0.273654  0.219860
1    0.10  1.000000  0.172134  0.273654  0.219860
2    1.00  1.000000  0.172133  0.273655  0.219861
3   10.00  1.000000  0.172119  0.273657  0.219875
4  100.00  0.999973  0.171994  0.273678  0.220013